ecom:
  jwt:
    key: 5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA # according to SHA-256 requirements
    algorithm: HS256
    issuer: http://localhost:8080
    expiresIn: 30
    refresh-token: 30
    jwtCookie: cookie
  onApp:
    userName: test
    userPassword: tesT2&!@kdfK
    userEmail: test@gmail.com