name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ecommerce-414411
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and deploy to Cloud Run
        run: |
          gcloud builds submit --tag eu.gcr.io/ecommerce-414411/ecomapp-zalando
          gcloud run deploy ecomapp --image gcr.io/ecommerce-414411/your-image-name --platform managed --region europe-west10