name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.ECOMMERCE }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.ECOMMERCE }}/my-app:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.ECOMMERCE }}/my-app:$GITHUB_SHA

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-app-service --image gcr.io/${{ secrets.ECOMMERCE }}/my-app:$GITHUB_SHA --platform managed --region us-central1 --allow-unauthenticated
